#ifndef _COMMON_H_
#define _COMMON_H_

#define APP_NO_BOX FL_NO_BOX
#define APP_UP_BOX FL_GTK_UP_BOX
#define APP_DOWN_BOX FL_GTK_DOWN_BOX
#define APP_UP_FRAME FL_GTK_UP_FRAME
#define APP_DOWN_FRAME FL_GTK_DOWN_FRAME
#define APP_THIN_UP_BOX FL_GTK_THIN_UP_BOX
#define APP_THIN_DOWN_BOX FL_GTK_THIN_DOWN_BOX
#define APP_THIN_UP_FRAME FL_GTK_THIN_UP_FRAME
#define APP_THIN_DOWN_FRAME FL_GTK_THIN_DOWN_FRAME
#define APP_ROUND_UP_BOX FL_GTK_ROUND_UP_BOX
#define APP_ROUND_DOWN_BOX FL_GTK_ROUND_DOWN_BOX

#endif